language: python
python:
 - "3.4"
 - "3.5"
 - "3.6"
install:
 - pip install -r requirements.txt --use-mirrors
 - pip install -e .
 - pip install -r requirements-test.txt --use-mirrors
script: pytest --cov=spore_codec
after_success:
 - pip install coveralls
 - coveralls
