language: python
python:
 - "3.4"
 - "3.5"
 - "3.6"
install:
 - pip install -r requirements.txt
 - pip install -e .
 - pip install -r requirements-test.txt
script: pytest --cov=spore_codec
after_success:
 - pip install coveralls
 - coveralls
