language: python
python:
 - "3.4"
 - "3.5"
 - "3.6"
install:
 - pip install -rU requirements.txt
 - pip install -e .
 - pip install -rU requirements-test.txt
script:
 - py.test --cov=spore_codec
after_success:
 - pip install coveralls
 - coveralls
